services:
  mysql:
    image: mysql:8.0
    container_name: project_db
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: project_kozlova

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql-files/

volumes:
  mysql_data: